[package]
name = "ufoc"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "^0.7"
cortex-m-rt = "0.7.1"
defmt = "0.3.0"
defmt-rtt = "0.3.1"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }
cortex-m-rtic = "1"

[dependencies.stm32ral]
version = "0.7"
features = ["stm32g474", "rtic"]


