[default.probe]
protocol = "Swd"

[defaultflashing]
enabled = true
halt_afterwards = false
restore_unwritten_bytes = false

[default.rtt]
# Whether or not an RTTUI should be opened after flashing.
enabled = true
# A list of channel associations to be displayed. If left empty, all channels are displayed.
# formats are: String, Defmt, BinaryLE,
channels = [
    { up = 0, name = "defmt_name", format = "Defmt" },

    # How to enable Defmt formatting (https://github.com/knurling-rs/defmt)
    # (formats on host, not on microcontroller)?
    # microcontroller setup: https://github.com/knurling-rs/app-template
    # { up = 0, name = "defmt_name", format = "Defmt" },
]
# The duration in ms for which the logger should retry to attach to RTT.
timeout = 3000
# Whether timestamps in the RTTUI are enabled
show_timestamps = true

[default.general]
chip = "STM32G431KBUx"
chip_descriptions = []
log_level = "Info"

[default.gdb]
# Whether or not a GDB server should be opened after flashing.
enabled = true
# The connection string in host:port format wher the GDB server will open a socket.
gdb_connection_string = "127.0.0.1:1337"